version: '3'
services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_USER=lesson
            - POSTGRES_PASSWORD=lesson
            - POSTGRES_DATABASE=lesson
        restart: always
        command: postgres
    
    redis: 
        image: redis:alpine3.14
        container_name: redis
        ports: 
            - "6379:6379"